config/routes.rb
Rails.application.routes.draw do
  resources :time_logs
  resources :topics
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/time_log.rb
class TimeLog < ApplicationRecord
  belongs_to :topic

  validates_presence_of :time_spent, :description
  validates :time_spent, numericality: { greater_than_or_equal_to: 0 }
  validates :description, length: { minimum: 3, maximum: 200 }
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :user
  has_many :time_logs, dependent: :destroy

  validates :topic, presence: true, length: { minimum: 3, maximum: 100 }
  validates :theme, presence: true, length: { minimum: 3, maximum: 50 }
  validates :skill_set, presence: true, length: { minimum: 3, maximum: 50 }
  validates :estimation, numericality: { greater_than_or_equal_to: 0 }
  validates :xp, numericality: { greater_than_or_equal_to: 0 }

  validates :completed_at, presence: true, if: :completed?

  scope :completed, -> { where(completed: true) }
  scope :in_progress, -> { where(completed: false) }

  def complete!
    update(completed: true, completed_at: Time.current)
  end

  def in_progress?
    !completed
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :topics, dependent: :destroy

  validates_presence_of :name, :email, :password_digest
  validates :email, uniqueness: true
  validates :name, length: { minimum: 3, maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/time_logs_controller.rb
class TimeLogsController < ApplicationController
  before_action :set_time_log, only: %i[ show edit update destroy ]

  # GET /time_logs or /time_logs.json
  def index
    @time_logs = TimeLog.all
  end

  # GET /time_logs/1 or /time_logs/1.json
  def show
  end

  # GET /time_logs/new
  def new
    @time_log = TimeLog.new
  end

  # GET /time_logs/1/edit
  def edit
  end

  # POST /time_logs or /time_logs.json
  def create
    @time_log = TimeLog.new(time_log_params)

    respond_to do |format|
      if @time_log.save
        format.html { redirect_to @time_log, notice: "Time log was successfully created." }
        format.json { render :show, status: :created, location: @time_log }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @time_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /time_logs/1 or /time_logs/1.json
  def update
    respond_to do |format|
      if @time_log.update(time_log_params)
        format.html { redirect_to @time_log, notice: "Time log was successfully updated." }
        format.json { render :show, status: :ok, location: @time_log }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @time_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /time_logs/1 or /time_logs/1.json
  def destroy
    @time_log.destroy!

    respond_to do |format|
      format.html { redirect_to time_logs_path, status: :see_other, notice: "Time log was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_time_log
      @time_log = TimeLog.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def time_log_params
      params.expect(time_log: [ :topic_id, :time_spent ])
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: %i[ show edit update destroy ]

  # GET /topics or /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1 or /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics or /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: "Topic was successfully created." }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1 or /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: "Topic was successfully updated." }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1 or /topics/1.json
  def destroy
    @topic.destroy!

    respond_to do |format|
      format.html { redirect_to topics_path, status: :see_other, notice: "Topic was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def topic_params
      params.expect(topic: [ :user_id, :topic, :theme, :skill_set, :estimatio, :xp, :completed, :completed_at ])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to users_path, status: :see_other, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.expect(user: [ :name, :email, :password_digest ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/time_logs_helper.rb
module TimeLogsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Tracksmith" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/time_logs/_form.html.erb
<%= form_with(model: time_log) do |form| %>
  <% if time_log.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(time_log.errors.count, "error") %> prohibited this time_log from being saved:</h2>

      <ul>
        <% time_log.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :topic_id, style: "display: block" %>
    <%= form.number_field :topic_id %>
  </div>

  <div>
    <%= form.label :time_spent, style: "display: block" %>
    <%= form.text_field :time_spent %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/time_logs/_time_log.html.erb
<div id="<%= dom_id time_log %>">
  <p>
    <strong>Topic:</strong>
    <%= time_log.topic_id %>
  </p>

  <p>
    <strong>Time spent:</strong>
    <%= time_log.time_spent %>
  </p>

</div>

app/views/time_logs/edit.html.erb
<% content_for :title, "Editing time log" %>

<h1>Editing time log</h1>

<%= render "form", time_log: @time_log %>

<br>

<div>
  <%= link_to "Show this time log", @time_log %> |
  <%= link_to "Back to time logs", time_logs_path %>
</div>

app/views/time_logs/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Time logs" %>

<h1>Time logs</h1>

<div id="time_logs">
  <% @time_logs.each do |time_log| %>
    <%= render time_log %>
    <p>
      <%= link_to "Show this time log", time_log %>
    </p>
  <% end %>
</div>

<%= link_to "New time log", new_time_log_path %>

app/views/time_logs/new.html.erb
<% content_for :title, "New time log" %>

<h1>New time log</h1>

<%= render "form", time_log: @time_log %>

<br>

<div>
  <%= link_to "Back to time logs", time_logs_path %>
</div>

app/views/time_logs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @time_log %>

<div>
  <%= link_to "Edit this time log", edit_time_log_path(@time_log) %> |
  <%= link_to "Back to time logs", time_logs_path %>

  <%= button_to "Destroy this time log", @time_log, method: :delete %>
</div>

app/views/topics/_form.html.erb
<%= form_with(model: topic) do |form| %>
  <% if topic.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
        <% topic.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id %>
  </div>

  <div>
    <%= form.label :topic, style: "display: block" %>
    <%= form.text_field :topic %>
  </div>

  <div>
    <%= form.label :theme, style: "display: block" %>
    <%= form.text_field :theme %>
  </div>

  <div>
    <%= form.label :skill_set, style: "display: block" %>
    <%= form.text_field :skill_set %>
  </div>

  <div>
    <%= form.label :estimatio, style: "display: block" %>
    <%= form.text_field :estimatio %>
  </div>

  <div>
    <%= form.label :xp, style: "display: block" %>
    <%= form.number_field :xp %>
  </div>

  <div>
    <%= form.label :completed, style: "display: block" %>
    <%= form.checkbox :completed %>
  </div>

  <div>
    <%= form.label :completed_at, style: "display: block" %>
    <%= form.datetime_field :completed_at %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/topics/_topic.html.erb
<div id="<%= dom_id topic %>">
  <p>
    <strong>User:</strong>
    <%= topic.user_id %>
  </p>

  <p>
    <strong>Topic:</strong>
    <%= topic.topic %>
  </p>

  <p>
    <strong>Theme:</strong>
    <%= topic.theme %>
  </p>

  <p>
    <strong>Skill set:</strong>
    <%= topic.skill_set %>
  </p>

  <p>
    <strong>Estimatio:</strong>
    <%= topic.estimatio %>
  </p>

  <p>
    <strong>Xp:</strong>
    <%= topic.xp %>
  </p>

  <p>
    <strong>Completed:</strong>
    <%= topic.completed %>
  </p>

  <p>
    <strong>Completed at:</strong>
    <%= topic.completed_at %>
  </p>

</div>

app/views/topics/edit.html.erb
<% content_for :title, "Editing topic" %>

<h1>Editing topic</h1>

<%= render "form", topic: @topic %>

<br>

<div>
  <%= link_to "Show this topic", @topic %> |
  <%= link_to "Back to topics", topics_path %>
</div>

app/views/topics/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Topics" %>

<h1>Topics</h1>

<div id="topics">
  <% @topics.each do |topic| %>
    <%= render topic %>
    <p>
      <%= link_to "Show this topic", topic %>
    </p>
  <% end %>
</div>

<%= link_to "New topic", new_topic_path %>

app/views/topics/new.html.erb
<% content_for :title, "New topic" %>

<h1>New topic</h1>

<%= render "form", topic: @topic %>

<br>

<div>
  <%= link_to "Back to topics", topics_path %>
</div>

app/views/topics/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @topic %>

<div>
  <%= link_to "Edit this topic", edit_topic_path(@topic) %> |
  <%= link_to "Back to topics", topics_path %>

  <%= button_to "Destroy this topic", @topic, method: :delete %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :password_digest, style: "display: block" %>
    <%= form.text_field :password_digest %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

  <p>
    <strong>Password digest:</strong>
    <%= user.password_digest %>
  </p>

</div>

app/views/users/edit.html.erb
<% content_for :title, "Editing user" %>

<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Users" %>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<% content_for :title, "New user" %>

<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>